### ISSUE TITLE
withQuery() does not support dataProp option

### ISSUE THREAD

**Issue by bhunjadi** [cult-of-coders/grapher-react#14]
Hi, I've just updated grapher-react and am in process of cleaning deprecation warnings for createQueryContainer.

But I've noticed that it is not possible to pass dataProp option to withQuery.
This is implemented in createQueryContainer here: https://github.com/cult-of-coders/grapher-react/blob/40c0d8a6df1bfafdd97586d4b4a22c1896b7856a/legacy/createQueryContainer.js#L20

My question is if this is a design decision, meaning you don't want to support this parameter anymore?
 (Haven't seen such notice in changelog, though)
Otherwise, I can make a PR.

As I understand it:
1. checkOptions have to be updated to accept **dataProp** 
2. withQueryContainer should use that parameter instead of fixed **data** key; https://github.com/cult-of-coders/grapher-react/blob/40c0d8a6df1bfafdd97586d4b4a22c1896b7856a/lib/withQueryContainer.js#L42

**Comment by theodorDiaconu** [comment]
@bhunjadi I think we should have it, you're right, there shouldn't be any reason not to. But we have to be careful about it.

**Comment by bhunjadi** [comment]
Great, I'll try to do the PR next week.

**Comment by theodorDiaconu** [comment]
@bhunjadi I remember there was a reason for why I avoided it.... I don't remember which though.
