### ISSUE TITLE
Changing the way isLoading is handled

### ISSUE THREAD

**Issue by arlen-yu** [cult-of-coders/grapher-react#27]
Hi. Right now, it seems the way that `isLoading` is handled for reactive and non-reactive data is different. 

For reactive data, `isLoading: true` for initial load. If I change the filter, `isLoading: true` again while data is refetched.

For non-reactive, `isLoading: true` for initial load. If I refetch, `isLoading: false` even when data is being refetched.

Is this intended, or should `isLoading` be set to `true` while non-react data is refetching? I think I see where in the code this is handled, so I'd be happy to submit a pull request implementing this.

**Comment by theodorDiaconu** [comment]
Released 0.1.3 sorry for delay.
